# Usage: https://taskfile.dev/
version: '3'
tasks:
  run:
    cmds:
      - limactl start ./dev.yaml
  delete:
    cmds:
      - limactl stop dev && limactl delete dev
  ssh:
    cmds:
      - limactl shell dev
